# UPTEMPO Regridding Configuration
# Edit the values below to customize your workflow

year: 2024
species:
  - black-carbon
  - organic-carbon
  - ammonia
  - carbon-monoxide
  - sulphur-dioxide
  - isoprene
  - monoterpenes
CAMS_GLOB_ANT_dir: '/glade/derecho/scratch/lacey/MPAS_DEVEL/CAMS/'
CAMS_grid_file: '/glade/campaign/acom/MUSICA/MPAS/input/Gridinfo_CAMS-GLOB-ANT_c20240709.nc'
SERR_scrip_file: '/glade/campaign/acom/MUSICA/MPAS/input/mpas_scrip.163842.nc'
Regridding_weights_file: '/glade/derecho/scratch/lacey/UPTEMPO/EMIS/ESMF_Weight_CAMSv6.2_grid_to_MPAS.x1.163842.c20260417.nc'
dst_file_format: '/glade/derecho/scratch/lacey/UPTEMPO/EMIS/CAMS-GLOB-ANT_{year}_MPAS.x1.163842.grid.SPC.nc'
inp_file_format: '/glade/derecho/scratch/lacey/MPAS_DEVEL/CAMS/CAMS-GLOB-ANT_v6.2_SPC_{year}.nc'
sectors: []
sector_exclude: ['awb']

# list of sectors to subtract from ``sum`` when creating the MPAS file.
# these names must match variables in the original CAMS file; the code
# will simply subtract their arrays from the ``sum`` array before writing
# the output.  leave empty if you don't need any adjustments.
